version: '3'
services: 

  # influxdb:
  #   image: influxdb:1.8
  #   container_name: influxdb_k6
  #   restart: always
  #   ports: 
  #     - 8086:8086
  #   volumes: 
  #     - ./influxdb_data:/var/lib/influxdb
  #   environment: 
  #     - INFLUXDB_DB=k6_db
  #     - INFLUXDB_USERNAME=k6
  #     - INFLUXDB_PASSWORD=k6_password
  #     - K6_INFLUXDB_INSECURE=true

  k6:
    image: loadimpact/k6
    volumes:
      - .:/src/
    # depends_on: 
    #   - influxdb
    # environment:
    #   - K6_INFLUXDB_USERNAME=k6
    #   - K6_INFLUXDB_PASSWORD=k6_password
    #   - K6_OUT=influxdb=http://influxdb:8086/k6_db